name: CI with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests with JaCoCo
        run: mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent test

      - name: Generate JaCoCo Coverage Report
        run: mvn -B org.jacoco:jacoco-maven-plugin:report

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/index.html